### ISSUE TITLE
Please document which distributions are supported

### ISSUE THREAD

**Issue by probonopd** [maui-project/znx#1]
Please document which distributions are supported.

I have been using a system like this for years and have added support for many different distributions/live boot systems, maybe you can reuse some parts:
https://github.com/probonopd/SystemImageKit

**Comment by luis-lavaire** [comment]
Hi @probonopd.

SystemImageKit was an inspiring piece of code for `znx`, so thanks for creating it :grinning:! The idea is not to write distro-specific code (autodetection), but rather to try to gain mainstream adoption, and, primarily, support Nitrux. I hope that  at some point `znx` could become the standard way of distributing Linux-based operating systems.

Right now, the user is in charge (this is still a beta version) of creating the entry of each new system added (but I think I can reuse some code of SystemImageKit at least for now). This will undoubtedly change in the future.

Right now I'm more focused on implementing the mechanisms for updating and installing new images.

Thanks for your comment! It's very welcome!

Cheers!

**Comment by probonopd** [comment]
[AppImageUpdate](https://github.com/AppImage/AppImageUpdate), when used with [type 1 update information](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-1-image-format), should be all that is needed to update ISOs... let me know if the meaning of the above is unclear and I should elaborate.

**Comment by luis-lavaire** [comment]
Again, thanks for your help and interest on this project. :+1: 

I was thinking about something very similar to what AppImageUpdate does (I mean, that the image has its own information and that `znx` just reads it and perform the proper action based on it). The needed information is the following:

- Update URL: The location of the next release of the ISO, or a standard one in the case of rolling-release distros. That URL should point to a `.zsync` file.
- Boot information: This should be a file with the bootloader entries and appropriate kernel parameters. Very similar to the loopback file found on several distributions already, but it should be on a standard location (`/boot/loopback.cfg`, for example) and modified a little to fit with `znx`.

Those fields are the ones that I have thought about so far.

I expect to implement both things in `znx`, because using AppImageUpdate just to read a single field of the ISO file is an overkill (I really appreciate your help and suggestions, so please understand why I am kindly refusing to use AppImageUpdate. It's a matter of keeping `znx` as simple and coherent as possible). I will use zsync(2) for downloading the deltas. I think that a file could be included inside the ISO file and be read by `znx` for performing the update.

I think that it's an excellent approach to make the ISO image host its own data, for the sake of decentralization. That's a "MUST-HAVE" feature in `znx`.

Thanks a lot for your time and suggestions! I appreciate them.

**Comment by probonopd** [comment]
@luis-lavaire I understand you want a _simple_ solution using zsync, and you _can_ use update information and `/boot/loopback.cfg` for exactly what you are describing.

You literally only need to put the string `zsync|http://server.domain/path/your.iso.zsync` in the ISO 9660 Volume Descriptor field (offset 33651) of your ISO, and upload both the iso and the zsync file to `http://server.domain/path/your.iso` and `http://server.domain/path/your.iso.zsync`. It will __just work__.

**Comment by luis-lavaire** [comment]
@probonopd, first of all, thanks for understanding what I am trying to do. :grin: 

I knew the purpose of the `loopback.cfg` file, but I wasn't shure if there was a standard path to find it. It was until today that I read this lines [here](https://www.supergrubdisk.org/wiki/Loopback.cfg):
 
> The loopback.cfg file must be found at the path /boot/grub/loopback.cfg.

...which is very helpful to know. And, of course, makes things easier.

> Please, please, please use the standard loopback.cfg. Only if every distribution supports the same format we can get some cross-distro sanity in the Linux desktop.

And I was not trying to create a new way of doing things. I was trying to create the standard that is already suggested there. :sweat_smile: And, as I mentioned, I didn't knew about the standard location. So, yes, the standard path of `loopback.cfg` will be used in `znx`.

I have to read more about the Volume Descriptor field and how to read it. Any advice here? I'm looking for something like a `grep` or similar to achieve this. It would make it very easy to use the returned value within a shell script.

**Comment by probonopd** [comment]
It is at offset 33651 of your ISO.

You can write it with

`echo "zsync|http://server.domain/path/your.iso.zsync" | dd of="your.iso" bs=1 seek=33651 count=512 conv=notrunc 2>/dev/null
`

You can clear it with

`dd if=/dev/zero of="your.iso" bs=1 seek=33651 count=512 conv=notrunc`

To read it, I leave it as an exercise for you - but rest assured that AppImageUpdate already can read it and can update the ISO file for you, with no development work on your side needed :-)

**Comment by probonopd** [comment]
> I'm planning to pack znx as an AppImage when it's ready, so I don't think that using AppImageUpdate can help me (Because it is an AppImage too! And packing an AppImage inside an AppImage... 😄).

Packing an AppImage inside an AppImage can be done and works. But it may be cleaner to extract the "inner" AppImage and combine it with the contents of the "outer" AppImage, and finally make one AppImage that contains both applications.

> For managing the ISO files updates, using a simple dd + grep command is all what I need 

Yes, but why code all that yourself? The original version of AppImageUpdate [was written in bash](https://github.com/AppImage/AppImageUpdate/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate) but we then decided to write it "properly".

`appimageupdatetool` is a command line application. https://github.com/AppImage/AppImageUpdate/releases

> For managing the ISO files updates, using a simple dd + grep command is all what I need (I'm planning to use busybox inside the AppImage to save space).

You don't need to put the shell interpreter into the AppImage if it can reasonably be assumed that `/bin/bash` is available on all target systems.

**Comment by luis-lavaire** [comment]
> Packing an AppImage inside an AppImage can be done and works.

I thought it was possible, but not the best approach. As you say, the best way would be to unpack one of them and repack that one alongside the other.

> Yes, but why code all that yourself?

To "keep it simple". It's not *that* much code for it. At most 10 lines of code (at most) will do the work and will be cleaner and more coherent than using another application embedded on the first. It would be "easier" to just run `./AppImageUpdate ...`, but I would really prefer to implement it in the script.

Regarding `busybox`... My intention for including it is not for provinding an interpreter. It has several utilities that I want to use and don't want to mess up with dozens of libraries that the GNU tools would pull in (also increasing the size of the application).

I will notify you when the expected behaviour is achieved. Keep an eye on this issue. Thanks a lot for your help.

Best regards. :grin:

**Comment by luis-lavaire** [comment]
Any ISO image that provides the `/boot/grub/loopback.cfg` file (it doesn't need to have GRUB2's MBR, it could be SYSLINUX, for instance; just the configuration file needs to be there.) can be booted with `znx`. We will not try to support edge cases. The [standard](https://www.supergrubdisk.org/wiki/Loopback.cfg) (not created by us) should be adopted by distro developers.
